.PHONY: all install-mac uninstall-mac symlink-mac

all: install-mac symlink-mac

install-mac:
	@echo "Installing ghostty..."
	@bash setup/mac/install.sh

uninstall-mac:
	@echo "Uninstalling ghostty..."
	@bash setup/mac/uninstall.sh

symlink-mac:
	@echo "Symlinking ghostty..."
	@bash setup/mac/symlink.sh
