.PHONY: all install-mac uninstall-mac symlink-mac

all: install-mac symlink-mac

install-mac:
	@echo "Installing tmux..."
	@bash setup/mac/install.sh

uninstall-mac:
	@echo "Uninstalling tmux..."
	@bash setup/mac/uninstall.sh

symlink-mac:
	@echo "Symlinking tmux..."
	@bash setup/mac/symlink.sh
